version: "1"

name: "transient-behavior-requirement-optimizer"

services:

    tbverifier:
        image: ghcr.io/cambio-project/transient-behavior-verifier:latest
        ports:
            - 8083:5000
        networks:
            - dashboardNetwork

    tqproprefiner:
        image: ghcr.io/cambio-project/transient-behavior-requirement-refiner:latest
        ports:
            - 8080:80
        networks:
            - dashboardNetwork

    proxy:
        build:
            context: ./proxy
            dockerfile: Dockerfile
            network: host
        ports:
            - 8070:8070
        networks:
            - dashboardNetwork
        depends_on:
            - tqproprefiner
        extra_hosts:
            - host.docker.internal:host-gateway

networks:
    dashboardNetwork:
