version: "1"

name: "transient-behavior-requirement-optimizer"

services:
  dashboard:
    image: ghcr.io/cambio-project/transient-behavior-requirement-refiner:latest
    ports:
      - 8080:80

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile_podman
      network: host
    ports:
      - 3000:3000
    networks:
      - dashboardNetwork
    depends_on:
      - dashboard
    extra_hosts:
      - host.container.internal:host-gateway

networks:
  dashboardNetwork:
